# 자동 생성 파일 — 수동 수정 금지.
# manage/generate/generate_api_client.py 재실행으로 갱신하세요.

"""API 코드 -> 함수 매핑 (CLI 등에서 코드로 함수를 동적으로 찾을 때 사용)."""

from src.api import (
    account,
    chart,
    investor_chart,
    market_info,
    order,
    price_info,
    rank_info,
    reserve_order,
    stock_info,
    withdraw,
)

REGISTRY = {
    "GSA10020": {
        "function": price_info.gsa10020,
        "name": "체결",
        "module": "price_info",
        "required": [],
        "optional": ["krx_cd", "is_cd", "rcrd_c"],
    },
    "GSA10150": {
        "function": rank_info.gsa10150,
        "name": "거래량상위",
        "module": "rank_info",
        "required": [],
        "optional": ["krx_cd", "std_dy", "vlm", "is_cnt"],
    },
    "GSA10170": {
        "function": rank_info.gsa10170,
        "name": "시가총액상위",
        "module": "rank_info",
        "required": [],
        "optional": ["krx_cd", "is_cnt"],
    },
    "GSA10600": {
        "function": market_info.gsa10600,
        "name": "해외시세분석",
        "module": "market_info",
        "required": [],
        "optional": ["frex_clsf", "clsf", "rnk", "is_cnt"],
    },
    "GSC10060": {
        "function": chart.gsc10060,
        "name": "통합차트",
        "module": "chart",
        "required": [],
        "optional": ["krx_cd", "is_cd", "chrt_clsf", "bndl", "mdfy_stk_prc_use_f", "rcrd_c", "srch_strt_dy", "clsf"],
    },
    "GSS10030": {
        "function": price_info.gss10030,
        "name": "현재가",
        "module": "price_info",
        "required": [],
        "optional": ["krx_cd", "is_cd"],
    },
    "GSS10040": {
        "function": price_info.gss10040,
        "name": "호가",
        "module": "price_info",
        "required": [],
        "optional": ["krx_cd", "is_cd"],
    },
    "GSS10180": {
        "function": rank_info.gss10180,
        "name": "신고_신저",
        "module": "rank_info",
        "required": [],
        "optional": ["krx_cd", "clsf", "clsf2", "std_dy", "vlm", "is_cnt"],
    },
    "IVA10370": {
        "function": market_info.iva10370,
        "name": "증시주변자금동향",
        "module": "market_info",
        "required": [],
        "optional": [],
    },
    "IVA60140": {
        "function": market_info.iva60140,
        "name": "세계지수",
        "module": "market_info",
        "required": [],
        "optional": ["lnd_clsf"],
    },
    "IVA60190": {
        "function": market_info.iva60190,
        "name": "환율종합",
        "module": "market_info",
        "required": [],
        "optional": [],
    },
    "IVM10050": {
        "function": stock_info.ivm10050,
        "name": "기업개요",
        "module": "stock_info",
        "required": [],
        "optional": ["is_cd"],
    },
    "IVM30010": {
        "function": rank_info.ivm30010,
        "name": "업종랭킹",
        "module": "rank_info",
        "required": [],
        "optional": ["mkt_clsf"],
    },
    "IVS10910": {
        "function": rank_info.ivs10910,
        "name": "시가대비등락률 상위",
        "module": "rank_info",
        "required": [],
        "optional": ["mkt_clsf", "inq_cnt", "srt_clsf"],
    },
    "IVS10920": {
        "function": rank_info.ivs10920,
        "name": "시가총액 상위",
        "module": "rank_info",
        "required": [],
        "optional": ["inq_cnt"],
    },
    "IVS11190": {
        "function": rank_info.ivs11190,
        "name": "기간외등락률 순위",
        "module": "rank_info",
        "required": [],
        "optional": ["mkt_clsf", "srt_clsf", "thdy_bdy_clsf", "inq_cnt"],
    },
    "IVS11560": {
        "function": chart.ivs11560,
        "name": "통합차트",
        "module": "chart",
        "required": [],
        "optional": ["info_ccd", "mkt_clsf", "chrt_clsf", "minute_tck_indx", "is_cd", "inq_clsf", "strt_dy", "inq_cnt"],
    },
    "IVSA0070": {
        "function": price_info.ivsa0070,
        "name": "시장종합",
        "module": "price_info",
        "required": [],
        "optional": [],
    },
    "IVU10020": {
        "function": rank_info.ivu10020,
        "name": "매매 상위",
        "module": "rank_info",
        "required": [],
        "optional": ["excg_clsf", "mkt_clsf", "invstr_ccd", "prd_clsf", "rnk_clsf"],
    },
    "IVU10070": {
        "function": price_info.ivu10070,
        "name": "호가",
        "module": "price_info",
        "required": [],
        "optional": ["is_cd", "ovtm_mkt_clsf"],
    },
    "IVU10080": {
        "function": price_info.ivu10080,
        "name": "체결",
        "module": "price_info",
        "required": [],
        "optional": ["excg_clsf", "is_cd", "ovtm_mkt_clsf", "inq_cnt"],
    },
    "IVU10140": {
        "function": price_info.ivu10140,
        "name": "현재가",
        "module": "price_info",
        "required": [],
        "optional": ["excg_clsf", "shrt_cd"],
    },
    "IVU10210": {
        "function": rank_info.ivu10210,
        "name": "거래대금 상위",
        "module": "rank_info",
        "required": [],
        "optional": ["excg_clsf", "mkt_clsf", "thdy_bdy_clsf", "inq_cnt", "srt_clsf"],
    },
    "IVU10240": {
        "function": rank_info.ivu10240,
        "name": "등락률 상위",
        "module": "rank_info",
        "required": [],
        "optional": ["excg_clsf", "mkt_clsf", "inq_cnt", "srt_clsf"],
    },
    "IVU10270": {
        "function": rank_info.ivu10270,
        "name": "급등_급락 상위",
        "module": "rank_info",
        "required": [],
        "optional": ["excg_clsf", "mkt_clsf", "inq_cnt", "up_dwn_ccd", "minute_dy_ccd", "minute_dy_unt"],
    },
    "IVU10280": {
        "function": rank_info.ivu10280,
        "name": "거래량 상위",
        "module": "rank_info",
        "required": [],
        "optional": ["excg_clsf", "mkt_clsf"],
    },
    "IVU10420": {
        "function": investor_chart.ivu10420,
        "name": "거래원",
        "module": "investor_chart",
        "required": [],
        "optional": ["excg_clsf", "is_cd"],
    },
    "IVU10430": {
        "function": investor_chart.ivu10430,
        "name": "투자자",
        "module": "investor_chart",
        "required": [],
        "optional": ["excg_clsf", "is_cd", "strt_dt", "end_dt", "amt_q_clsf", "trd_clsf", "acml_clsf"],
    },
    "IVU10450": {
        "function": investor_chart.ivu10450,
        "name": "프로그램",
        "module": "investor_chart",
        "required": [],
        "optional": ["excg_clsf", "is_cd", "amt_q_clsf", "prd_clsf", "inq_cnt"],
    },
    "IVU10550": {
        "function": rank_info.ivu10550,
        "name": "신고_신저",
        "module": "rank_info",
        "required": [],
        "optional": ["excg_clsf", "mkt_clsf", "inq_cnt", "nw_stk_lw_ccd", "std_clsf", "prd_clsf", "excd_clsf"],
    },
    "SIAM4983": {
        "function": stock_info.siam4983,
        "name": "종목기본정보",
        "module": "stock_info",
        "required": [],
        "optional": ["Record1"],
    },
    "SIQM4900": {
        "function": stock_info.siqm4900,
        "name": "종목기본정보",
        "module": "stock_info",
        "required": [],
        "optional": ["stnd_is_cd"],
    },
    "SKAM2101": {
        "function": order.skam2101,
        "name": "매도_매수주문",
        "module": "order",
        "required": [],
        "optional": ["trd_dl_ccd", "is_cd", "frgn_ordr_typ_cd", "frgn_ordr_q", "frgn_ordr_prc_p4"],
    },
    "SKAM2102": {
        "function": order.skam2102,
        "name": "정정_취소주문",
        "module": "order",
        "required": [],
        "optional": ["crct_cncl_clsf", "is_cd", "orgn_ordr_no", "frgn_ordr_prc_p4"],
    },
    "SKAM2201": {
        "function": order.skam2201,
        "name": "소수점매도_매수주문",
        "module": "order",
        "required": [],
        "optional": [
            "trd_dl_ccd",
            "is_cd",
            "amt_q_clsf",
            "tv_s_est_f",
            "frgn_ordr_typ_cd",
            "crncy_ccd",
            "ordr_amt",
            "dcml_ordr_q_p6",
            "frgn_ordr_prc_p4",
        ],
    },
    "SKAM2202": {
        "function": order.skam2202,
        "name": "소수점취소주문",
        "module": "order",
        "required": [],
        "optional": ["orgn_ordr_no"],
    },
    "SKQM2106": {
        "function": account.skqm2106,
        "name": "주문가능금액조회",
        "module": "account",
        "required": [],
        "optional": ["stnd_is_cd"],
    },
    "SKQM3350": {
        "function": account.skqm3350,
        "name": "주문가능금액현황조회",
        "module": "account",
        "required": [],
        "optional": [],
    },
    "SPAO2104": {
        "function": reserve_order.spao2104,
        "name": "주식예약주문미국",
        "module": "reserve_order",
        "required": [],
        "optional": ["is_cd", "trd_dl_ccd", "ordr_typ_cd", "ordr_q", "frgn_ordr_prc_p4", "strt_tm", "end_tm"],
    },
    "SPAO2106": {
        "function": reserve_order.spao2106,
        "name": "예약주문취소미국",
        "module": "reserve_order",
        "required": [],
        "optional": ["is_cd", "trd_clsf", "ordr_typ", "ordr_q", "frgn_ordr_prc_p4", "cncl_ordr_no"],
    },
    "SPQM2103": {
        "function": account.spqm2103,
        "name": "주문체결조회",
        "module": "account",
        "required": [],
        "optional": ["ccls_clsf", "ordr_dt", "dl_clsf", "nxt_key"],
    },
    "SPQM2204": {
        "function": account.spqm2204,
        "name": "체결미체결 조회",
        "module": "account",
        "required": [],
        "optional": ["strt_ordr_dt", "end_ordr_dt", "ccls_clsf", "trd_clsf", "stnd_is_cd", "dl_clsf", "nxt_key"],
    },
    "SPQM2205": {
        "function": account.spqm2205,
        "name": "매매정산 현황",
        "module": "account",
        "required": [],
        "optional": [
            "strt_ordr_dt",
            "end_ordr_dt",
            "trd_clsf",
            "stnd_is_cd",
            "krw_unty_mgn_rqst_f",
            "dl_clsf",
            "nxt_key",
        ],
    },
    "SPQM2206": {
        "function": account.spqm2206,
        "name": "매매손익 당일",
        "module": "account",
        "required": [],
        "optional": ["ordr_dt", "stnd_is_cd", "std_crncy_f", "exch_r_aplc_f", "frgn_stk_mgn_ccd", "dl_clsf", "nxt_key"],
    },
    "SPQM2207": {
        "function": account.spqm2207,
        "name": "매매손익 기간별",
        "module": "account",
        "required": [],
        "optional": ["stnd_is_cd", "std_crncy_f", "exch_r_aplc_f", "frgn_stk_mgn_ccd", "dl_clsf", "nxt_key"],
    },
    "SPQM2226": {
        "function": account.spqm2226,
        "name": "해외주식계좌잔고평가조회",
        "module": "account",
        "required": [],
        "optional": ["std_crncy_f", "exch_r_aplc_f", "fee_clsf", "cn_f", "nxt_key"],
    },
    "SPQM3390": {
        "function": account.spqm3390,
        "name": "계좌증거금조회",
        "module": "account",
        "required": [],
        "optional": [],
    },
    "SPQN5472": {
        "function": account.spqn5472,
        "name": "소수점주문가능금액조회",
        "module": "account",
        "required": [],
        "optional": [],
    },
    "SPQO2105": {
        "function": reserve_order.spqo2105,
        "name": "예약주문조회",
        "module": "reserve_order",
        "required": [],
        "optional": ["rsrv_dt", "stnd_is_cd", "trd_clsf", "krw_unty_mgn_rqst_f", "cn_key"],
    },
    "SRQM3051": {
        "function": account.srqm3051,
        "name": "계좌권리 발생내역",
        "module": "account",
        "required": [],
        "optional": ["strt_dt", "rgt_clsf", "is_cd", "nxt_key"],
    },
    "SSAM0831": {
        "function": reserve_order.ssam0831,
        "name": "예약주문접수",
        "module": "reserve_order",
        "required": [],
        "optional": ["ordr_jb_clsf", "is_cd", "ordr_uprc", "ordr_q", "ordr_ccd", "strt_dt", "end_dt", "mkt_tm_ccd"],
    },
    "SSAM1801": {
        "function": order.ssam1801,
        "name": "매도주문",
        "module": "order",
        "required": [],
        "optional": ["mkt_tm_clsf", "is_cd", "ordr_q", "ordr_uprc", "ordr_ccd", "sor_ordr_ccd"],
    },
    "SSAM1802": {
        "function": order.ssam1802,
        "name": "매수주문",
        "module": "order",
        "required": [],
        "optional": ["mkt_tm_clsf", "is_cd", "ordr_q", "ordr_uprc", "ordr_ccd", "sor_ordr_ccd"],
    },
    "SSAM1805": {
        "function": order.ssam1805,
        "name": "정정주문",
        "module": "order",
        "required": [],
        "optional": [
            "mkt_tm_clsf",
            "is_cd",
            "ordr_q",
            "ordr_uprc",
            "ordr_ccd",
            "crct_clsf",
            "orgn_ordr_no",
            "sor_ordr_ccd",
        ],
    },
    "SSAM1806": {
        "function": order.ssam1806,
        "name": "취소주문",
        "module": "order",
        "required": [],
        "optional": ["is_cd", "ordr_q", "crct_clsf", "orgn_ordr_no"],
    },
    "SSAM5762": {
        "function": order.ssam5762,
        "name": "소수점 매도주문",
        "module": "order",
        "required": [],
        "optional": ["is_cd", "ordr_q_p6", "ordr_amt", "dcml_ordr_std_ccd", "tv_s_est_f"],
    },
    "SSAM5763": {
        "function": order.ssam5763,
        "name": "소수점 매수주문",
        "module": "order",
        "required": [],
        "optional": ["is_cd", "ordr_q_p6", "ordr_amt", "dcml_ordr_std_ccd"],
    },
    "SSAM5764": {
        "function": order.ssam5764,
        "name": "소수점 주문취소",
        "module": "order",
        "required": [],
        "optional": [
            "dmstc_stk_dcml_trd_jb_ccd",
            "ordr_sqc",
            "ordr_dt",
            "bnf_is_cd",
            "trd_dl_ccd",
            "dmstc_stk_dcml_ordr_sq",
        ],
    },
    "SSQM0004": {
        "function": account.ssqm0004,
        "name": "예수금내역",
        "module": "account",
        "required": [],
        "optional": ["is_no"],
    },
    "SSQM0831": {
        "function": reserve_order.ssqm0831,
        "name": "예약주문처리 조회",
        "module": "reserve_order",
        "required": [],
        "optional": ["ordr_dt", "nxt_key", "trd_clsf", "hndl_clsf", "tv_rv_ccd", "end_dt", "is_cd"],
    },
    "SSQM0834": {
        "function": reserve_order.ssqm0834,
        "name": "예약주문접수 조회",
        "module": "reserve_order",
        "required": [],
        "optional": ["nxt_key", "strt_dt", "end_dt", "is_cd"],
    },
    "SSQM1801": {
        "function": account.ssqm1801,
        "name": "보유주식 조회",
        "module": "account",
        "required": [],
        "optional": ["inq_clsf", "is_no", "mkt_tm_ccd", "nxt_key"],
    },
    "SSQM1802": {
        "function": account.ssqm1802,
        "name": "매수주문가능금액",
        "module": "account",
        "required": [],
        "optional": ["is_no"],
    },
    "SSQM2121": {
        "function": account.ssqm2121,
        "name": "매매정산현황",
        "module": "account",
        "required": [],
        "optional": ["trd_dt", "clsf", "stmt_dt", "nxt_key"],
    },
    "SSQM2341": {
        "function": account.ssqm2341,
        "name": "체결미체결 조회",
        "module": "account",
        "required": [],
        "optional": ["ccls_clsf", "ordr_dt", "nxt_key"],
    },
    "SSQM2392": {
        "function": account.ssqm2392,
        "name": "매매손익현황",
        "module": "account",
        "required": [],
        "optional": ["is_no", "ordr_dt_from", "ordr_dt_to", "nxt_key"],
    },
    "SSQM2442": {
        "function": account.ssqm2442,
        "name": "실현손익현황",
        "module": "account",
        "required": [],
        "optional": ["is_cd", "inq_strt_dt", "inq_end_dt", "md_clsf", "nxt_key"],
    },
    "SSQM2932": {
        "function": account.ssqm2932,
        "name": "잔고현황 조회(결제기준)",
        "module": "account",
        "required": [],
        "optional": ["inq_clsf", "excg_mktpr_ccd"],
    },
    "SSQM2952": {
        "function": account.ssqm2952,
        "name": "잔고현황 조회(체결기준)",
        "module": "account",
        "required": [],
        "optional": ["excg_mktpr_ccd"],
    },
    "SSQM5765": {
        "function": account.ssqm5765,
        "name": "소수점매매 조회",
        "module": "account",
        "required": [],
        "optional": ["trd_clsf", "trd_strt_dt", "trd_end_dt", "is_cd", "nxt_key"],
    },
    "SWQA2301": {
        "function": withdraw.swqa2301,
        "name": "거래내역 조회",
        "module": "withdraw",
        "required": [],
        "optional": ["inq_clsf", "strt_dt", "end_dt", "is_no", "nxt_key", "srt_clsf"],
    },
    "SWQM2412": {
        "function": withdraw.swqm2412,
        "name": "거래내역 조회 상세",
        "module": "withdraw",
        "required": [],
        "optional": ["inq_dt", "dl_sq", "nxt_key"],
    },
    "SWQN2302": {
        "function": withdraw.swqn2302,
        "name": "출금가능금액 조회",
        "module": "withdraw",
        "required": [],
        "optional": ["ccd"],
    },
    "SZQM0771": {
        "function": market_info.szqm0771,
        "name": "장운영상태",
        "module": "market_info",
        "required": [],
        "optional": [],
    },
}


def list_apis(module: str | None = None):
    """등록된 API 코드/이름 목록. module 지정 시 해당 모듈만 필터링."""
    items = REGISTRY.items()
    items = [(c, v) for c, v in items if v["module"] == module] if module else list(items)
    return [(code, v["name"], v["module"]) for code, v in items]
